repos:
  - repo: local
    hooks:
      - id: add-license
        name: Add License Headers
        entry: addlicense
        language: system
        types: [go]
        args: ["-c", "Ksctl Authors"]

      - id: go-fmt
        name: go fmt
        entry: gofmt -l -w .
        language: system
        types: [go]

      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        types: [go]
        pass_filenames: false

      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
