name: Bug Report
description: Report a bug to help us improve
title: "[Bug Report]: "
labels: ["kind/bug", "needs-triage", "priority/high"]

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for reporting a bug.** Your feedback is valuable to us. Please fill in as much of the template below as you're able, to help us better understand and fix the bug.

  - type: input
    id: bug-title
    attributes:
      label: Bug Title
      description: Provide a concise title that summarizes the bug.
      placeholder: Short and descriptive title of the bug
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the bug. Be as detailed as possible.
      placeholder: 1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Describe the expected outcome after following the steps above.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened instead.
      placeholder: Describe the actual outcome after following the steps above.
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Include details like the ksctl version, operating system, and the version of the software in which the bug occurred.
      placeholder: e.g., ksctl cli on Windows 10, version 1.3 
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional context about the problem here. Screenshots or error logs are very helpful.
      placeholder: Any additional information, screenshots, or logs that might help us understand the problem better.
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: "Please confirm the following:"
      options:
        - label: I have searched the existing issues and this is a new and unique bug report.
          required: true
        - label: I agree to provide follow-up information if needed.
          required: true

  - type: checkboxes
    id: updates
    attributes:
      label: Scope of changes
      description: what all subprojects will be affected?
      options:
        - label: Cli
        - label: UI
        - label: Docs

  - type: checkboxes
    id: agreement
    attributes:
      label: Agreement
      description: By submitting this feature proposal, you agree to engage in constructive discussion and follow our [Contribution Guidelines](https://docs.ksctl.com/docs/contribution-guidelines/)
      options:
        - label: I agree to engage in constructive discussion and follow the Contribution Guidelines.
          required: true

