name: ci-test-go

on:
  push:
    paths:
      - "pkg/**"
      - "cmd/**"
    branches: [main]
  pull_request:
    paths:
      - "pkg/**"
      - "cmd/**"
    branches: [main]

jobs:
  go-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: check gofmt pkg dir
        working-directory: pkg
        run: gofmt -s -w -d $(find . -type f -name '*.go' -print)

      - name: check gofmt cmd dir
        working-directory: cmd
        run: gofmt -s -w -d $(find . -type f -name '*.go' -print)

      # TODO: Add linter
      # - name: check golint
      #   run: $#@$@
