name: goreleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Install Cosign 
        uses: sigstore/cosign-installer@main

      - name: Set the value
        id: set_environment
        run: |
          echo "CURR_DATE=$(date '+%d-%m-%Y')" >> $GITHUB_ENV
          echo "CURR_VER=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATE: ${{ env.CURR_DATE }}
          VERSION: ${{ env.CURR_VER }}
