name: Generate and Sync CLI Docs

on:
  push:
    branches:
      - main
    paths:
      - 'cli/**'  # Adjust this to match your CLI code structure
      - 'gen/docs.md/**'  # If the generator is in a separate directory
  
  workflow_dispatch:

jobs:
  generate-and-sync-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout CLI repository
      uses: actions/checkout@v4
      with:
        path: cli-repo

    - name: Checkout Docs repository
      uses: actions/checkout@v4
      with:
        path: docs-repo
        repository: 'ksctl/docs'
        ref: 'main'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Generate Documentation
      working-directory: cli-repo
      run: |
        make gen-docs

    - name: Sync Generated Docs
      run: |
        # Copy generated docs
        cp -rv cli-repo/gen/docs.md/. docs-repo/content/en/docs/develop/Reference/.

    - name: Commit and Push Changes
      working-directory: docs-repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add content/en/cli-reference
        git diff --quiet && git diff --staged --quiet || (git commit -m "chore(cicd): Update CLI documentation" && git push)
