name: Testing Build process
on:
  push:
    paths:
      - "cmd/**"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
    branches: [main]
  pull_request:
    paths:
      - "cmd/**"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: go version
      - name: Build and install the latest version
        run: |
          make install_linux
          ksctl version

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: go version
      # TODO: add support to check for the M1 chip as well
      - name: Build and install the latest version on intel chip
        run: |
          make install_macos_intel
          ksctl version
