name: Testing Logger
on:
  push:
    paths:
      - "pkg/logger/**"
      - "go.mod"
      - "go.sum"
    branches: [main]
  pull_request:
    paths:
      - "pkg/logger/**"
      - "go.mod"
      - "go.sum"
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: go version
      - name: testing
        working-directory: pkg/logger
        run: |
          go test -v ./...
