name: "Test Functionality of the Mock cli"
on:
  pull_request:
    paths:
      - '.github/workflows/test-mock.yml'
      - 'cli/**'
      - 'scripts/**'
      - 'go.mod'
      - 'go.sum'
    types: [ labeled ]
    branches: [ main ]
  push:
    paths:
      - 'scripts/**'
      - 'cli/**'
      - '.github/workflows/test-mock.yml'
      - 'go.mod'
      - 'go.sum'
    branches: [ main ]
jobs:
  ksctl-cli:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    if: ${{ github.event.label.name == 'pr/lgtm' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
    runs-on: ${{ matrix.os }}
    env:
      KSCTL_FAKE_FLAG_ENABLED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v2

      - name: build ksctl linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          make install_linux
          ksctl version


      - name: build ksctl macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          make install_macos_intel
          ksctl version

      - name: civo create
        run: |
          ksctl create civo -n demo -r LON1 --nodeSizeMP "g4s.kube.small" --verbose -1 --approve
          ksctl create ha-civo -n ha-demo --nodeSizeDS "fake.small" --nodeSizeLB "fake.small" --nodeSizeCP "fake.small" --nodeSizeWP "fake.small" -r LON1 --verbose -1 --approve
      - name: azure create
        run: |
          ksctl create azure -n demo -r fake --nodeSizeMP "fake" --verbose -1 --approve
          ksctl create ha-azure -n ha-demo --nodeSizeDS "fake" --nodeSizeLB "fake" --nodeSizeCP "fake" --nodeSizeWP "fake" -r fake --verbose -1 --approve

      - name: local create
        run: |
          ksctl create local -n demolocal --verbose -1 --approve

      - name: civo get
        run: |
          ksctl get -p civo
      - name: azure get
        run: |
          ksctl get -p azure
      - name: all
        run: |
          ksctl get

      - name: civo switch
        run: |
          ksctl switch -p civo -n demo -r LON1
          ksctl switch -p ha-civo -n ha-demo -r LON1
          
      - name: azure switch
        run: |
          ksctl switch -p azure -n demo -r fake
          ksctl switch -p ha-azure -n ha-demo -r fake


      - name: civo scale up and down
        run: |
          ksctl delete ha-civo delete-nodes -n ha-demo --noWP 0 -r LON1 --approve -v -1
          ksctl create ha-civo add-nodes -n ha-demo --noWP 1 --nodeSizeWP "fake.small" -r LON1 -v -1 --approve

      - name: azure scale up and down
        run: |
          ksctl delete ha-azure delete-nodes -n ha-demo --noWP 0 -r fake --approve -v -1
          ksctl create ha-azure add-nodes -n ha-demo --noWP 1 --nodeSizeWP "fake" -r fake -v -1 --approve

      - name: civo delete
        run: |
          ksctl delete civo -n demo -r LON1 -v -1 --approve
          ksctl delete ha-civo -n ha-demo -r LON1 -v -1 --approve


      - name: azure delete
        run: |
          ksctl delete azure -n demo -r fake -v -1 --approve
          ksctl delete ha-azure -n ha-demo -r fake -v -1 --approve

      - name: local delete
        run: |
          ksctl delete local -n demolocal -v -1 --approve
